# Generated by Django 3.2.16 on 2025-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.JSONField(default=list),
        ),
    ]
