apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # 对于Docker Desktop，这会自动映射到localhost的一个端口
  # 如果你使用Minikube或其他环境，也可以使用 NodePort