apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  # Experiment Service 数据库配置
  MYSQL_DATABASE_EXPERIMENT: lab_platform_experiment
  MYSQL_USER_EXPERIMENT: course_experiment
  MYSQL_PASSWORD_EXPERIMENT: course_experiment

  # Forum Service 数据库配置
  MYSQL_DATABASE_FORUM: lab_platform_forum
  MYSQL_USER_FORUM: course_forum
  MYSQL_PASSWORD_FORUM: course_forum

  # Materials Service 数据库配置
  MYSQL_DATABASE_MATERIALS: lab_platform_materials
  MYSQL_USER_MATERIALS: course_materials
  MYSQL_PASSWORD_MATERIALS: course_materials

  # User Service 数据库配置
  MYSQL_DATABASE_USER: lab_platform_user
  MYSQL_USER_USER: course_user
  MYSQL_PASSWORD_USER: course_user

  # Notice Service 数据库配置
  MYSQL_DATABASE_NOTICE: lab_platform_notice
  MYSQL_USER_NOTICE: course_notice
  MYSQL_PASSWORD_NOTICE: course_notice

  # Root 用户（共用）
  MYSQL_ROOT_PASSWORD: course