version: '3.8'

services:
  experiment-db:
    image: postgres:14
    environment:
      POSTGRES_DB: experiment_db
      POSTGRES_USER: experiment_user
      POSTGRES_PASSWORD: password
    volumes:
      - experiment-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  experiment-service:
    build: .
    command: gunicorn experiment_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    environment:
      DEBUG: "True"
      EXPERIMENT_DB_NAME: experiment_db
      EXPERIMENT_DB_USER: experiment_user
      EXPERIMENT_DB_PASSWORD: password
      EXPERIMENT_DB_HOST: experiment-db
      USER_SERVICE_URL: http://user-service:8000
    ports:
      - "8001:8000"
    depends_on:
      - experiment-db

volumes:
  experiment-db-data: