apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-backend
  labels:
    app: course-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-backend
  template:
    metadata:
      labels:
        app: course-backend
    spec:
      containers:
        - name: backend
          image: course-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "server.settings"
            - name: DB_ENGINE
              value: "django.db.backends.mysql"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: course-backend
  labels:
    app: course-backend
spec:
  selector:
    app: course-backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
