apiVersion: v1
kind: Service
metadata:
  name: mysql # 其他应用将通过这个名称连接
  labels:
    app: mysql
spec:
  selector:
    app: mysql # 选择标签为 app=mysql 的 Pod
  ports:
    - port: 3306 # Service 暴露的端口
      targetPort: 3306 # 容器监听的端口