apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  MYSQL_DATABASE: lab_platform
  MYSQL_USER: course
  MYSQL_PASSWORD: course
  MYSQL_ROOT_PASSWORD: course
