# Generated by Django 5.2.1 on 2025-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.SmallIntegerField(choices=[(1, '安全公告'), (2, '课程通知'), (3, '设备维护'), (4, '实验发布')], default=2, verbose_name='类型')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('author_id', models.IntegerField(verbose_name='作者ID')),
                ('experiment_id', models.IntegerField(blank=True, null=True, verbose_name='关联实验ID')),
                ('readers', models.JSONField(default=list, verbose_name='已读用户ID列表')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
                'ordering': ['-is_top', '-date'],
            },
        ),
    ]
