# Generated by Django 5.2.1 on 2025-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "安全公告"),
                            (2, "课程通知"),
                            (3, "设备维护"),
                            (4, "实验发布"),
                        ],
                        default=2,
                        verbose_name="类型",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                ("is_top", models.BooleanField(default=False, verbose_name="是否置顶")),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告管理",
                "ordering": ["-is_top", "-date"],
            },
        ),
    ]
