# Generated by Django 5.2.1 on 2025-06-08 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0002_initial"),
        ("notice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="experiments.experiment",
                verbose_name="关联实验",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="readers",
            field=models.ManyToManyField(
                blank=True,
                related_name="read_notices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="已读用户",
            ),
        ),
    ]
