# Generated by Django 5.2.1 on 2025-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资料标题")),
                ("description", models.TextField(verbose_name="资料描述")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("video", "视频教程"),
                            ("doc", "文档资料"),
                            ("image", "图表素材"),
                            ("code", "代码示例"),
                            ("slide", "幻灯片"),
                        ],
                        max_length=10,
                        verbose_name="资料类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="materials/%Y/%m/%d/", verbose_name="资料文件"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "学习资料",
                "verbose_name_plural": "学习资料",
                "ordering": ["-created_at"],
            },
        ),
    ]
